// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAEA.Infrastructure.Database.Context;

#nullable disable

namespace SAEA.Infrastructure.Migrations
{
    [DbContext(typeof(SAEAContext))]
    [Migration("20251024031911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAEA.Domain.Models.Desk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ST_DESK_ID");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("NB_CAPACITY");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ST_CODE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ST_NAME");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ST_ROOM_ID");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UN_DESK_CODE");

                    b.HasIndex("RoomId");

                    b.ToTable("TB_DESKS", (string)null);
                });

            modelBuilder.Entity("SAEA.Domain.Models.OperatingBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ST_OPERATING_BLOCK_ID");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DT_END_DATE_TIME");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ST_REASON");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ST_RESOURCE_ID");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int")
                        .HasColumnName("NB_RESOURCE_TYPE");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DT_START_DATE_TIME");

                    b.HasKey("Id");

                    b.HasIndex("EndDateTime")
                        .HasDatabaseName("IX_OPERATING_BLOCKS_END");

                    b.HasIndex("StartDateTime")
                        .HasDatabaseName("IX_OPERATING_BLOCKS_START");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("IX_OPERATING_BLOCKS_RESOURCE");

                    b.HasIndex("ResourceType", "ResourceId", "StartDateTime", "EndDateTime")
                        .HasDatabaseName("IX_OPERATING_BLOCKS_RESOURCE_PERIOD");

                    b.ToTable("TB_OPERATING_BLOCKS", (string)null);
                });

            modelBuilder.Entity("SAEA.Domain.Models.OperatingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ST_OPERATING_HOURS_ID");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("NB_DAY_OF_WEEK");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("DT_END_TIME");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ST_RESOURCE_ID");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int")
                        .HasColumnName("NB_RESOURCE_TYPE");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("DT_START_TIME");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek")
                        .HasDatabaseName("IX_OPERATING_HOURS_DAY");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("IX_OPERATING_HOURS_RESOURCE");

                    b.ToTable("TB_OPERATING_HOURS", (string)null);
                });

            modelBuilder.Entity("SAEA.Domain.Models.Pavilion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ST_PAVILION_ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ST_CODE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ST_NAME");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UN_PAVILION_CODE");

                    b.ToTable("TB_PAVILIONS", (string)null);
                });

            modelBuilder.Entity("SAEA.Domain.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ST_ROOM_ID");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("NB_CAPACITY");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ST_CODE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ST_NAME");

                    b.Property<Guid>("PavilionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ST_PAVILION_ID");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UN_ROOM_CODE");

                    b.HasIndex("PavilionId");

                    b.ToTable("TB_ROOMS", (string)null);
                });

            modelBuilder.Entity("SAEA.Domain.Models.Desk", b =>
                {
                    b.HasOne("SAEA.Domain.Models.Room", "Room")
                        .WithMany("Desks")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SAEA.Domain.Models.Room", b =>
                {
                    b.HasOne("SAEA.Domain.Models.Pavilion", "Pavilion")
                        .WithMany("Rooms")
                        .HasForeignKey("PavilionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pavilion");
                });

            modelBuilder.Entity("SAEA.Domain.Models.Pavilion", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SAEA.Domain.Models.Room", b =>
                {
                    b.Navigation("Desks");
                });
#pragma warning restore 612, 618
        }
    }
}
